#!/bin/bash
# make-cellar-app.sh — wrap any launch-engine.sh invocation into a clickable
# /Applications/cellar Games/<name>.app bundle.
#
# Usage:
#   make-cellar-app.sh <profile-id> "<game-dir-name>" ["<display name>"]
#
# Examples:
#   make-cellar-app.sh frostbite-multi "Need for Speed Heat"
#   make-cellar-app.sh rage-rockstar "Grand Theft Auto V" "GTA V"
#   make-cellar-app.sh unreal-engine-4-5 "Elden Ring"
#
# Generates a per-game launcher under ~/.cellar/launchers/ that execs
# scripts/launch-engine.sh with the right args baked in, then hands it
# to make-game-app.sh.
set -euo pipefail

CELLAR_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MASTER="$CELLAR_ROOT/scripts/launch-engine.sh"
MAKER="$CELLAR_ROOT/scripts/make-game-app.sh"
WRAP_DIR="$HOME/.cellar/launchers"

PROFILE="${1:?profile id required (see profiles.json)}"
GAME="${2:?game dir name required (relative to ~/Games-source/)}"
NAME="${3:-$GAME}"

if [ ! -x "$MASTER" ]; then
  echo "missing master launcher: $MASTER" >&2
  exit 1
fi
if [ ! -x "$MAKER" ]; then
  echo "missing $MAKER" >&2
  exit 1
fi
if ! command -v jq >/dev/null 2>&1; then
  echo "jq not found, install with: brew install jq" >&2
  exit 2
fi
# Validate that the profile actually exists, so we fail loudly here rather
# than later in the launcher's own jq lookup.
if ! jq -e ".profiles[] | select(.id == \"$PROFILE\")" "$CELLAR_ROOT/profiles.json" >/dev/null 2>&1; then
  echo "profile id not found in profiles.json: $PROFILE" >&2
  echo "available profiles:" >&2
  jq -r '.profiles[].id' "$CELLAR_ROOT/profiles.json" >&2
  exit 1
fi

mkdir -p "$WRAP_DIR"
slug() { echo "$1" | tr 'A-Z ' 'a-z-' | tr -dc 'a-z0-9-' | sed 's/--*/-/g; s/^-//; s/-$//'; }
WRAP="$WRAP_DIR/launch-$(slug "$NAME").sh"
cat > "$WRAP" <<EOF
#!/bin/bash
# auto-generated by scripts/make-cellar-app.sh for "$NAME"
exec /bin/bash "$MASTER" "$PROFILE" "$GAME" "\$@"
EOF
chmod +x "$WRAP"
echo "wrapper: $WRAP"

"$MAKER" "$NAME" "$WRAP"
echo "done. app lands at /Applications/cellar Games/$NAME.app"
